# Site settings
title: Andrew Avitabile, PhD Student
description: Welcome to my site!

# Theme settings
remote_theme: jekyll/coffeescript

# Other possible configurations
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
author: Andrew Avitabile
email: yaj3ma@virginia.edu
